FORMAT: 1A
HOST: http://veteran-rating-calculator.apiblueprint.org/

# veteran-rating-calculator

Veteran Disability Rating Calculator takes 1 or more percentage ratings and returns a cumulative disability rating and an estimate disability rating. Ratings are calculated using the table at the bottom of this page https://www.benefits.va.gov/compensation/rates-index.asp.


## Cumulative Disability Rating Calculator [/calculate]

### Calculate [POST]

This will return a Veteran's cumulative disability and estimated disability rating. It takes a JSON
object containing 1 or more percentage values (ratings).

+ Request (application/json)

        {
            "ratings": [
                20,
                60,
                30
            ]
        }

+ Response 201 (application/json)

    + Body

            {
                "cumulative_disability_rating": 81,
                "estimated_disability_rating": 80
            }